### ISSUE TITLE
qlBitRate.qlgenerator disables Icon cover art previews in finder for all mp3 files!

### ISSUE THREAD

**Issue by galaxy-nomad** [jordansaints/qlBitRate#4]
Hello,
Thanks for this wonderful plugin. I had the qlBitRate.qlgenerator installed but I noticed that all of the cover art previews were missing in finder for my mp3 files. I removed the qlBitRate.qlgenerator plugin and the artwork icon previews are restored. Is there a workaround to get cover art to display with qlBitRate.qlgenerator installed?

**Comment by sch4llfl3g3l** [comment]
Hello,
confirm this on OS X 10.10.5 (found the workaround by myself, then detected this issue while searching on Google). Removing the qlbitrate plugin resolves the missing cover art problem.

**Comment by galaxy-nomad** [comment]
Hi sch4llfl3g3l,
Are you saying that upgrading to 10.10.5 resolves the issue and that you can see cover art with the qlBitRate plugin installed? I've moved back to Snow Leopard so I can't test the fix myself but it woud be nice to know if 10.10.5 fixes the issue if I need to upgrade in the future.

**Comment by sch4llfl3g3l** [comment]
Hi cyberfunk,

unfortunately the answer is "no", it does not work in 10.10.5 - only if you **remove** the qlbitrate plugin (and do a `killall Finder`, **then** the cover art is back again.
If this doesn't work properly (as in my case some mp3 still displayed only an app's icon), then delete icon caches from _/private/var/folders_.
**Conclusion**: the issue still persists. I guess that (in theory) qlbitrate should catch all requests to mp3 tags, then process them and after this should transfer the non-implemented tags back to QL / Finder. This seems to be not working, at least in 10.10.5. Please regard this an assumption, i didn't investigate the source code.

**Comment by 1-61803** [comment]
@jordansaints, it seems that, if you preview an mp3 file with embedded artwork with the `QLGenerator Audio.qlgenerator`, the bitrate will show, but not the artwork.

**Comment by jordansaints** [comment]
@1-61803 yes that seems to be the prevailing issue. This code is years old at this point and probably can be updated to work properly, but I doubt I'll have the time.

@sch4llfl3g3l thanks for that investigation and the fix instructions, I'm sure they've been helpful to many people since you posted. Feel free to throw up a PR if you have any time to explore the source code! I haven't looked at QuickLook extensions in years, and won't have much time to update this one unfortunately.

**Comment by 1-61803** [comment]
@jordansaints, maybe you can add to the `README` a link to this issue and that YMMV. In any case, you could try a quick debug with `qlmanage` to see if you can identify a quick fix or not.

**Comment by pkuczynski** [comment]
@jordansaints I like this plugin, but not displaying artwork is a major issue. Do you have any time to fix it?

**Comment by pkuczynski** [comment]
@cyberfunk why would u close this? The bug is still there...

**Comment by galaxy-nomad** [comment]
I don't expect this will be updated by @jordansaints. His last reply was two years ago 2017 and with the way Apple is locking down the system with Catalina I assume system level tweaks like these will eventually be impossible. You're welcome to open a new thread or find a developer to update the tweak for you if you'd like.
